# Generated by Django 5.1.5 on 2025-02-03 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='player2',
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='winner',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
